environment:
  matrix:
    - perl: 5.30.1.1
    - perl: 5.28.2.1
    - perl: 5.26.2.1
    - perl: 5.24.4.1
    - perl: 5.22.3.1
    - perl: 5.20.3.3
    - perl: 5.18.4.1
    ##failed##- perl: 5.16.3.1  # choco package points to outdated download URL
    - perl: 5.16.3.20170202
    - perl: 5.14.4.1
    ##failed##- perl: 5.12.3.0  # choco package points to outdated download URL
    ##failed##- perl: 5.12.3.1  # choco package points to outdated download URL
  my_secret:
    secure: jaDctcFyMpD/cnbje/T3BRr0JAlglYhW7NI/4nQZBXs=

skip_tags: true

cache:
  #- C:\strawberry -> appveyor.yml

install:
  - IF NOT DEFINED perl set perl=default
  - echo install Perl v%perl%...
  - IF NOT EXIST "C:\strawberry" (IF /I %perl%==default (cinst strawberryperl) ELSE (cinst strawberryperl --version %perl%) )
  - IF NOT EXIST "chocologs" MKDIR chocologs
  - IF EXIST "c:\ProgramData\chocolatey\logs" COPY /Y "c:\ProgramData\chocolatey\logs" "chocologs"
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -le "print qq(installed perl v$])"
  - echo Make sure c:\temp and c:\tmp exist for Data::UUID
  - IF NOT EXIST "c:\temp" MKDIR "c:\temp"
  - IF NOT EXIST "c:\tmp" MKDIR "c:\tmp"
  - echo install required CPAN repos
  - cpanm --installdeps .
  - cpanm App::cpanminus::reporter
  - IF EXIST "C:\Users\appveyor\.cpanm\build.log" COPY /Y "C:\Users\appveyor\.cpanm\build.log" cpanm.build.log
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt .\av-cpanreporter\metabase_id.json.enc -secret %my_secret%
  - cmd: appveyor-tools\secure-file -decrypt .\av-cpanreporter\config.ini.enc -secret %my_secret%
  - IF NOT EXIST "C:\users\appveyor\.cpanreporter" MKDIR "C:\users\appveyor\.cpanreporter"
  - IF EXIST av-cpanreporter\metabase_id.json COPY "av-cpanreporter\metabase_id.json" "C:\users\appveyor\.cpanreporter\metabase_id.json"
  - IF EXIST av-cpanreporter\config.ini COPY "av-cpanreporter\config.ini" "C:\users\appveyor\.cpanreporter\config.ini"

build_script:
  - echo build using Perl=%perl%...
  - perl -le "print qq(build with perl v$])"
  - if exist "Makefile.PL" (perl Makefile.PL)
  - if exist "Makefile"    (perl -MConfig -le "system $Config{make}")

test_script:
  - echo test Perl=%perl%...
  - perl -le "print qq(test with perl v$])"
  - if exist "Makefile" (perl -MConfig -le "system $Config{make}, 'test'") ELSE (prove -l t)
  - FOR /f "delims=" %%G in (ModuleList.txt) DO (
        echo cpanm %%G
        & cpanm %%G
        & dir "C:\Users\appveyor\.cpanm\build.log"
        & echo cpanm-reporter
        & cpanm-reporter
        & echo =-=-=-=-=-=-=-=-=-=-=
    )

artifacts:
  - path: chocologs
  - path: cpanm.build.log
